image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
- cmd: >-
    cd RedisConfigs

    redis-server --service-name redis-master --service-install master.conf

    redis-server --service-name redis-slave --service-install slave.conf

    redis-server --service-name redis-secure --service-install secure.conf

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - docs/*

nuget:
  disable_publish_on_pr: true

build_script:
  - ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -Version "$env:APPVEYOR_REPO_TAG_NAME" -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true

test: off
artifacts:
- path: .\.nupkgs\*.nupkg
