image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
- cmd: >-
    cd RedisConfigs\3.0.503

    redis-server.exe --service-install --service-name "redis-master" "..\master.conf"

    redis-server.exe --service-install --service-name "redis-slave" "..\slave.conf"

    redis-server.exe --service-install --service-name "redis-secure" "..\secure.conf"

    redis-server.exe --service-start --service-name "redis-master"

    redis-server.exe --service-start --service-name "redis-slave"

    redis-server.exe --service-start --service-name "redis-secure"

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - docs/*

nuget:
  disable_publish_on_pr: true

build_script:
  - ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -Version "$env:APPVEYOR_REPO_TAG_NAME" -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true

test: off
artifacts:
- path: .\.nupkgs\*.nupkg
